# Generated by Django 5.2.4 on 2025-08-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiftTemplate',
            fields=[
                ('LiftTemplateId', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField(default=10)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('lift_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LiftTracker.liftname')),
            ],
        ),
    ]
