# Generated by Django 5.2.4 on 2025-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiftTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifttemplate',
            name='id',
        ),
        migrations.AddField(
            model_name='lifttemplate',
            name='LifTTemplateId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
