# Generated by Django 5.2.4 on 2025-07-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiftTracker', '0002_remove_lifttemplate_id_lifttemplate_lifttemplateid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifttemplate',
            old_name='LifTTemplateId',
            new_name='LiftTemplateId',
        ),
    ]
