# Generated by Django 5.2.4 on 2025-08-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiftTracker', '0003_rename_lifttemplateid_lifttemplate_lifttemplateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifttemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lifttemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lifttemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lifttemplate',
            name='weight',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
